package constants

// ERR code Global
const (
	ERR_SUCCESS    = "00"
	ERR_SUCCESS_MSG = "SUCCESS.."

	EC_TRANSACTION_FAILED = "01"
	EC_TRANSACTION_FAILED_DESC = "Transaction Failed"

	ERR_PARAMETER     = "02"
	ERR_PARAMETER_MSG = "Error Parameter"

	ERR_EMPTY_INPUT = "01"
	ERR_EMPTY_INPUT_MSG = "Error, empty body"

	ERR_UNMARSHAL     = "03"
	ERR_UNMARSHAL_MSG = "Error, unmarshall body Request"

	ERR_CODE_04		 	= "04"
	ERR_CODE_04_MSG		= "Fail sent to kafka"

	EC_FAIL_DATA_NOTFOUND		 	= "05"
	EC_FAIL_DATA_NOTFOUND_DESC		= "Data not found"

	EC_FAIL_DATA_TIPE_BISNIS_NOTFOUND		 	= "05"
	EC_FAIL_DATA_TIPE_BISNIS_NOTFOUND_DESC		= "TIPE BISNIS NOT REGISTERED"

	EC_FAIL_SAVE = "06";
	EC_FAIL_SAVE_DESC = "FAILED SAVE TO DB ";

	EC_FAIL_DATE = "07"
	EC_FAIL_DATE_MSG = "Start Date > End Date"

	EC_FAIL_SEND_TO_HOST = "08";
	EC_FAIL_SEND_TO_HOST_DESC = "FAILED SEND TO HOST ";

	EC_FAIL_DELETE = "09";
	EC_FAIL_DELETE_DESC = "FAILED DELETE DATA ";

	EC_FAIL_PENDING_APPROVAL = "10";
	EC_FAIL_PENDING_APPROVAL_DESC = "THIS DATA HAS PENDING APPROVAL";
	EC_FAIL_HAS_BEEN_APPROVED = "11";
	EC_FAIL_HAS_BEEN_APPROVED_DESC = "THIS DATA HAS BEEN APPROVED";
	EC_FAIL_HAS_BEEN_REJECTED = "12";
	EC_FAIL_HAS_BEEN_REJECTED_DESC = "THIS DATA HAS BEEN REJECTED";

	EC_FAIL_CSV_FILE = "13";
	EC_FAIL_CSV_FILE_DESC = "FAILED TO SEND DATA CSV: ";

	EC_FAIL_UPLOAD_XSLX_FILE = "14"
	EC_FAIL_UPLOAD_XSLX_FILE_DESC = "FAILED UPLOAD FILE XLSX"

	EC_FAIL_RENAME_XSLX_FILE = "15"
	EC_FAIL_RENAME_XSLX_FILE_DESC = "FAILED RENAME FILE XLSX"

	EC_FAIL_SEND_PUSH_NOTIF		 	= "16"
	EC_FAIL_SEND_PUSH_NOTIF_DESC		= "Failed Send Push Notif"

	EC_FAILED_SAVE_OWNER = "17"
	EC_FAILED_SAVE_OWNER_DESC = "Failed save owner"

	EC_FAILED_SAVE_MERCHANT = "17"
	EC_FAILED_SAVE_MERCHANT_DESC = "Failed save owner"

	EC_FAILED_SAVE_MERCHANT_BANK_LOAN = "17"
	EC_FAILED_SAVE_MERCHANT_BANK_LOAN_DESC = "Failed save merchant bank loan"

	EC_FAILED_GENERATE_QR = "18"
	EC_FAILED_GENERATE_QR_DESC = "Failed Generate QR"

	EC_FAILED_BLAST_NOTIF = "19"
	EC_FAILED_BLAST_NOTIF_DESC = "Failed Send blast notif host"

	EC_INVALID_PASSWORD = "20"
	EC_INVALID_PASSWORD_DESC = "Invalid Password"

	EC_FAILED_SAVE_PARTNER_LINK = "21"
	EC_FAILED_SAVE_PARTNER_LINK_DESC = "Failed save partner link"

)


const (
	ON_PROGRESS = "ON_PROGRESS"
	DONE		= "DONE"
	FORMAT_ERROR = "CSV file format is not appropriate"
	FORMAT_XLSX_ERROR = "Xlsx file format is not appropriate"
	FAILED = "FAILED"

)

const (
	PENDING = "PENDING"
	APPROVED = "APPROVED"
	REJECTED = "REJECTED"
)

const (
	RETRY = "retry"
)


const (
	HttpMethodGet    = "GET"
	HttpMethodPost   = "POST"
	HttpMethodPut    = "PUT"
	HttpMethodDelete = "DELETE"
)

const (
	OttomartClearSession = "OTTOMART_CLEAR_SESSION"
	MinioUpload = "MINIO_UPLOAD"
)

const (
	ACTIVE = "active"
	IN_ACTIVE = "inactive"
)

const (
	SEND_NOTIF = "SEND_NOTIF"
)

const (
	INQUIRY_INTERNAL = "INQUIURY_INTERNAL"
	INQUIRY_EXTERNAL = "INQUIRY_EXTERNAL"
)

const (
	MANDIRI_BANK_CODE = "008"
)

const (
	BLAST_NOTIF_SEND_ALL="BLAST_NOTIF_SEND_ALL"
)