package status_registration

const (

	NONE = "NONE"

	VVIP_VERIFIER_START_VIEW = "VVIP_VERIFIER_START_VIEW"
	VIP_VERIFIER_START_VIEW = "VIP_VERIFIER_START_VIEW"
	VERIFIER_START_VIEW = "VERIFIER_START_VIEW"
)

