package models

type MerchantWip struct {
	ID                    int64       `json:"id"`
	ActionType            int         `json:"actionType"`
	ApprovalStatus        int         `json:"approvalStatus"`
	LatestApproval        string      `json:"latestApproval"`
	LatestApprover        string      `json:"latestApprover"`
	LatestSuggestion      string      `json:"latestSuggestion"`
	LatestSuggestor       string      `json:"latestSuggestor"`
	Status                int64       `json:"status"`
	Version               int         `json:"version"`
	AgentID               string      `json:"agentId`
	AgentName             string      `json:"agentName"`
	Alamat                string      `json:"alamat"`
	APIKey                string      `json:"apiKey"`
	ApprovalNote          string      `json:"approvalNote"`
	HostStatus            string      `json:"hostStatus"`
	InstitutionID         string      `json:"institutionId"`
	JamOperasional        string      `json:"jamOperasional"`
	JenisLokasiBisnis     string      `json:"jenisLokasiBisnis"`
	JenisUsaha            string      `json:"jenisUsaha"`
	KabupatenKota         string      `json:"kabupatenKota"`
	Kecamatan             string      `json:"kecamatan"`
	Kelurahan             string      `json:"kelurahan"`
	KtpPath               string      `json:"ktpPath"`
	Latitude              string      `json:"latitude"`
	LogoPath              string      `json:"logoPath"`
	LokasiBisnis          string      `json:"lokasiBisnis"`
	Longitude             string      `json:"longitude"`
	MerchantCategoryCode  string      `json:"merchantCategoryCode"`
	MerchantGroupID       int         `json:"merchantGroupId"`
	MerchantOutletID      string      `json:"merchantOutletId"`
	MerchantPan           string      `json:"merchantPan"`
	MerchantPhoto2Path    string      `json:"merchantPhoto2Path"`
	MerchantPhotoPath     string      `json:"merchantPhotoPath"`
	MerchantType          string      `json:"merchantType"`
	Notes                 string      `json:"notes"`
	PostalCode            string      `json:"postalCode"`
	Provinsi              string      `json:"provinsi"`
	Reason                string      `json:"reason"`
	ReferralCode          string      `json:"referralCode"`
	SecretID              string      `json:"secretId"`
	SecretQuestion        string      `json:"secretQuestion"`
	SecretQuestionAnswer  string      `json:"secretQuestionAnswer"`
	SelfiePath            string      `json:"selfiePath"`
	SignPath              string      `json:"signPath"`
	StatusRegistration    int         `json:"statusRegistration"`
	StoreName             string      `json:"storeName"`
	StorePhoneNumber      string      `json:"storePhoneNumber"`
	WfID                  int         `json:"wfId"`
	WorkflowExecutionID   int         `json:"workflowExecutionId"`
	OwnerWip              OwnerWIP     `json:"ownerWIP"`
	SettlementConfigWip   SettlementConfigWip         `json:"settlementConfigWIP"`
	IDMerchant            int64       `json:"idMerchant"`
	Level                 string 	  `json:"level"`
	Mcc                   string      `json:"mcc"`
	NMid                  string 	  `json:"nMid`
	KategoriBisnis        string 	  `json:"kategoriBisnis"`
}
type OwnerWIP struct {
	ID                    int64    `json:"id"`
	OwnerAddress          string `json:"ownerAddress"`
	OwnerFirstName        string `json:"ownerFirstName"`
	OwnerJenisKelamin     string `json:"ownerJenisKelamin"`
	OwnerKabupaten        string `json:"ownerKabupaten"`
	OwnerKecamatan        string `json:"ownerKecamatan"`
	OwnerKelurahan        string `json:"ownerKelurahan"`
	OwnerKodePos          string `json:"ownerKodePos"`
	OwnerLastName         string `json:"ownerLastName"`
	OwnerNamaIbuKandung   string `json:"ownerNamaIbuKandung"`
	OwnerNoID             string `json:"ownerNoID"`
	OwnerNoTelp           string `json:"ownerNoTelp"`
	OwnerPekerjaan        string `json:"ownerPekerjaan"`
	OwnerProvinsi         string `json:"ownerProvinsi"`
	OwnerRt               string `json:"ownerRt"`
	OwnerRw               string `json:"ownerRw"`
	OwnerTanggalExpiredID string `json:"ownerTanggalExpiredID"`
	OwnerTanggalLahir     string `json:"ownerTanggalLahir"`
	OwnerTelpLain         string `json:"ownerTelpLain"`
	OwnerTempatLahir      string `json:"ownerTempatLahir"`
	OwnerTipeID           string `json:"ownerTipeID"`
	OwnerTitle            string `json:"ownerTitle"`
}

type SettlementConfigWip struct {
	FmsFee                    int    `json:"fmsFee"`
	ID                        int64    `json:"id"`
	Mdr                       string `json:"mdr"`
	MdrCreditOffUs            int    `json:"mdrCreditOffUs"`
	MdrCreditOnUs             int    `json:"mdrCreditOnUs"`
	MdrDebitOffUs             int    `json:"mdrDebitOffUs"`
	MdrDebitOnUs              int    `json:"mdrDebitOnUs"`
	MdrEmoneyOffUs            int    `json:"mdrEmoneyOffUs"`
	MdrEmoneyOnUs             int    `json:"mdrEmoneyOnUs"`
	NamaBankTujuanSettlement  string `json:"namaBankTujuanSettlement"`
	NamaPemilikRekening       string `json:"namaPemilikRekening"`
	NoRekeningToko            string `json:"noRekeningToko"`
	OtherFee                  int    `json:"otherFee"`
	ProcessingConfiguration   string `json:"processingConfiguration"`
	ProcessingFee             string `json:"processingFee"`
	ProcessingFeeValue        int    `json:"processingFeeValue"`
	RentalEdcFee              int    `json:"rentalEdcFee"`
	ReportSettlementConfig    string `json:"reportSettlementConfig"`
	SendReportURL             string `json:"sendReportUrl"`
	SendReportVia             string `json:"sendReportVia"`
	SettlementConfig          string `json:"settlementConfig"`
	SettlementExecutionConfig string `json:"settlementExecutionConfig"`
	Status                    int    `json:"status"`
	TipeRekening              string `json:"tipeRekening"`
}